name: CI Front-end (Main)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sgcmapp/**'
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - 'sgcmapp/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Angular Setup
        working-directory: sgcmapp/
        run: npm install -g @angular/cli@17.3.8
      - name: Dependences
        working-directory: sgcmapp/
        run: npm install
      - name: build
        working-directory: sgcmapp/
        run: ng build
      - name: Test
        working-directory: sgcmapp/
        run: ng test --browsers=ChromeHeadless --no-watch
        
        